// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"github.com/swaggo/swag"
)

// Package docs Fiber Example API.
//
// This is a sample swagger for Fiber.
//
// Terms of Service: http://swagger.io/terms/
// Email: fiber@swagger.io
// License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//
// BasePath: /
// Version: 1.0
//
// swagger:meta

// Kullanıcı listeleme işlemi için Swagger notasyonları
// swagger:route GET /api/users users listUsers
// ListUsersHandler fonksiyonu ile kullanıcıları listeler.
// Responses:
//   200: []users.User
func ListUsersHandler() {}

// Kullanıcı detayları için Swagger notasyonları
// swagger:route GET /api/users/{id} users getUser
// GetUserHandler fonksiyonu ile belirtilen ID'ye sahip kullanıcının detaylarını getirir.
// Responses:
//   200: users.User
func GetUserHandler(id string) {}

// Kullanıcı oluşturma işlemi için Swagger notasyonları
// swagger:route POST /api/users users createUser
// CreateUserHandler fonksiyonu ile yeni bir kullanıcı oluşturur.
// Responses:
//   201: users.User
func CreateUserHandler() {}

// Kullanıcı güncelleme işlemi için Swagger notasyonları
// swagger:route PUT /api/users users updateUser
// UpdateUserHandler fonksiyonu ile belirtilen ID'ye sahip kullanıcının bilgilerini günceller.
// Responses:
//   200: users.User
func UpdateUserHandler(id string) {}

// Kullanıcı silme işlemi için Swagger notasyonları
// swagger:route DELETE /api/users users deleteUser
// DeleteUserHandler fonksiyonu ile belirtilen ID'ye sahip kullanıcıyı siler.
// Responses:
//   204:
func DeleteUserHandler(id string) {}

const docTemplate = `{
  "openapi": "3.0.0",
  "info": {
    "title": "User Management System API",
    "description": "User Management System API",
    "contact": {
      "email": "bugrayaktiyol@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://127.0.0.1:3001"
    }
  ],
  "tags": [
    {
      "name": "users",
      "description": "Operations on user data"
    }
  ],
  "paths": {
    "/api/users": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get a list of all users",
        "operationId": "listUsers",
        "responses": {
          "200": {
            "description": "A list of users",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/UserOutput"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Create a new user",
        "operationId": "createUser",
        "requestBody": {
          "description": "User object that needs to be added",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserInput"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserOutput"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get a user by ID",
        "operationId": "getUserById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of the user to get",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserOutput"
                }
              }
            }
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Update a user by ID",
        "operationId": "updateUserById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of the user to update",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Updated user object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserInput"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User updated successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserOutput"
                }
              }
            }
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "delete": {
        "tags": [
          "users"
        ],
        "summary": "Delete a user by ID",
        "operationId": "deleteUserById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of the user to delete",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "User deleted successfully"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UserInput": {
        "required": [
          "address",
          "age",
          "name",
          "tags"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "John Doe"
          },
          "age": {
            "type": "integer",
            "example": 25
          },
          "address": {
            "type": "string",
            "example": "123 Main St"
          },
          "tags": {
            "type": "string",
            "example": "cool,loser"
          }
        }
      },
      "UserOutput": {
        "type": "object",
        "properties": {
          "ID": {
            "type": "integer",
            "example": 1027
          },
          "Name": {
            "type": "string",
            "example": "Nadean Schwimmer"
          },
          "Age": {
            "type": "integer",
            "example": 20
          },
          "Address": {
            "type": "string",
            "example": "15726 Express Crossing"
          },
          "Tags": {
            "type": "string",
            "example": "music,loser"
          },
          "CreatedAt": {
            "type": "string",
            "format": "date-time"
          },
          "UpdatedAt": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "DeletedAt": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          }
        }
      }
    }
  }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3001",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Fiber Example API",
	Description:      "This is a sample swagger for Fiber.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
